### ISSUE TITLE
handle exit codes of the runner

### ISSUE THREAD

**Issue by ltalirz** [EPFLISICLSMO/aiida-codes#4]
if a computer already exists (has the same label),
result = cli_runner.invoke(cmd_computer.computer_setup, options)
returns:
<Result SystemExit(<ExitCode.CRITICAL: 1>,)>
(which correspond to the following warning in the command line:)
Critical: A computer called fidis-debug already exists. Use "verdi computer duplicate fidis-debug" to set up a new computer starting from the settings of fidis-debug.

Let's think what to do in this case.
For example we may want to write in the README to rename their old computers before, if the same label already exists

**Comment by danieleongari** [comment]
I will write a comment on that in the README of https://github.com/lsmo-epfl/aiida-lsmo-setup
